### ISSUE TITLE
Create announcement post for django india X Pydelhi meetup

### ISSUE THREAD

**Issue by DevilsAutumn** [djangoindia/no-code-contributions#1]
Need to create one post announcing the django india X pydelhi meetup happening at new delhi. we will be posting them on our social media.

Details(tentative):
When: 16 nov, 2pm-6pm
venue: TDB
regsiter link: https://www.djangoindia.org/events/django-india-x-pydelhi-meetup

how to contribute:
- fork repo
- Create a new folder under the graphics and desgin folder with the name as your github username.
- upload the post inside that folder with name as issue_number.jpg. If there are multiple files then append one incremental number after file name. 
- create a PR

**Comment by whyanshika** [comment]
I want to work on this
